### ISSUE TITLE
loop in installation

### ISSUE THREAD

**Issue by AdelSol75** [Magisk-Modules-Repo/G-VisualMod#10]
impossible to install it in One + 6t, whatever you choose I end up having an infinite installation. I have tried to change the name of the module, to install it as is and there is no way, it returns to put all the options from the beginning

**Comment by Gnonymous7** [comment]
you have to choose "Back" option until you get into main menu and found "Continue" option.
This "Continue" option wont appears if you havent select any mods

**Comment by Gnonymous7** [comment]
Install method will change on new update
