### ISSUE TITLE
Pill invisible mode disappeared

### ISSUE THREAD

**Issue by People-11** [Magisk-Modules-Repo/G-VisualMod#11]
I used to choose invisible mode for my pill, but the latest update don't have this option. I can't find it anywhere.

**Comment by Gnonymous7** [comment]
invisible is same as fullscreen

**Comment by People-11** [comment]
> invisible is same as fullscreen

Fullscreen mode invalid. Not working on my ROM

**Comment by Gnonymous7** [comment]
> > invisible is same as fullscreen
> 
> Fullscreen mode invalid. Not working on my ROM

please provide details and logs
