### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Shenron0** [Magisk-Modules-Repo/G-VisualMod#12]
Installing any version above 3.0 on OnePlus 7/7 Pro on OOS Beta 19 will cause apps with dark mode enabled by system default to crash. Only after uninstalling or downgrading back to 3.0 and below will fix this. And apps that are placed in the hidden space will also be plagued by this issue.

**Comment by Gnonymous7** [comment]
which mod did u install? can you check every mod u selected, which one is the problem

**Comment by Gnonymous7** [comment]
Old issue
