### ISSUE TITLE
Fullscreen mode leaves gap at some resolutions

### ISSUE THREAD

**Issue by richardmalone** [Magisk-Modules-Repo/G-VisualMod#13]
Hi there, firstly thank you for a great module. Since Google decided to get rid of adb overscan, this seems to be the only way to hide soft navigation buttons and keyboard gap on Android 11.

My system: Pixel C, LineageOS 18.1 (unofficial) by followmsi
Launcher: Taskbar
Magisk: Latest as of now +your module

Issue:  Certain display sizes leave a gap at the bottom when selecting fullscreen mode.  If I select 'default' display size, there is a gap which looks about the size of a 3-button navbar. If I select 'larger' as the screen size, there is no gap.

I thought for a while that this might be a problem with the launcher, but I have checked and the whole system sees that space as reserved, even though it is empty. I thought maybe your module doesn't expect such a large screen area as the Pixel C has an unusually high DPI and 3:2 aspect ratio.

Worth also mentioning that this same behaviour is seen with the 'Fullscreen/Immersive Gesture Mods for Android 10-11' magisk module. I imagine you use the same methods, so not suprising.

Screenshots below. Top is display size set to default, bottom is set to larger.

![Screenshot_20210104-110250_Taskbar](https://user-images.githubusercontent.com/6492842/103652151-9a575e00-4f5a-11eb-93e0-02eadf0219dc.png)
![Screenshot_20210104-110224_Taskbar](https://user-images.githubusercontent.com/6492842/103652176-a0e5d580-4f5a-11eb-9cfe-03de101bf1e2.png)

Thanks!

**Comment by Gnonymous7** [comment]
okay, thanks for reporting. will be fixed on the next update.

**Comment by Gnonymous7** [comment]
module updated, waiting for fix confirmation
