### ISSUE TITLE
A better way to set up different pill shapes for landscape and portrait modes

### ISSUE THREAD

**Issue by Jnss98b** [Magisk-Modules-Repo/G-VisualMod#14]
Currently, the only way to have different pill shapes for each screen orientation is to answer yes or no to the last step of selecting a pill shape which asks the user if they want to apply the selected pill shape to landscape mode. I don't know why anyone would answer no to that for any reason because why would you want the landscape pill to be smaller than the portrait pill. Ideally, the landscape pill should be wider than the portrait pill and that's simply not achievable currently. Instead of asking that, you should just let users set the pill shape for each screen orientation separately.

**Comment by Gnonymous7** [comment]
will add option in upcoming update, thanks for your suggestion!

**Comment by Jnss98b** [comment]
Thank you, I look forward to the update

**Comment by Gnonymous7** [comment]
updated!

**Comment by Jnss98b** [comment]
The custom landscape width doesn't work on my pixel 5 unfortunately

![Screenshot_20210129-114806](https://user-images.githubusercontent.com/24306400/106303340-05c5e000-6228-11eb-9e59-db76f875f2ab.png)
![Screenshot_20210129-114824](https://user-images.githubusercontent.com/24306400/106303343-05c5e000-6228-11eb-96bb-81eeec4b2150.png)

**Comment by Gnonymous7** [comment]
Did u tried lower value?

**Comment by Gnonymous7** [comment]
Please send logs

**Comment by Jnss98b** [comment]
[gvisualmod-verbose.log](https://github.com/Magisk-Modules-Repo/G-VisualMod/files/5897234/gvisualmod-verbose.log)
[gvisualmod.log](https://github.com/Magisk-Modules-Repo/G-VisualMod/files/5897235/gvisualmod.log)

**Comment by Jnss98b** [comment]
Also I tried using the default landscape value which was 29dp more than the portrait length but saw no difference either

![Screenshot_20210131-003200](https://user-images.githubusercontent.com/24306400/106375646-cd272300-635b-11eb-9005-a4282045eaa2.png)


[gvisualmod-verbose.log](https://github.com/Magisk-Modules-Repo/G-VisualMod/files/5899227/gvisualmod-verbose.log)
[gvisualmod.log](https://github.com/Magisk-Modules-Repo/G-VisualMod/files/5899228/gvisualmod.log)

**Comment by Jnss98b** [comment]
Sorry closed by accident

**Comment by Gnonymous7** [comment]
Are u using official pixel rom? I heard that its doesn't work well with gvm

**Comment by Jnss98b** [comment]
Yes

**Comment by Jnss98b** [comment]
How so? Shouldn't it be the one of the easiest of not the easiest to modify

**Comment by Gnonymous7** [comment]
does ur landscape length always follow portrait value?

**Comment by Jnss98b** [comment]
Yes
