### ISSUE TITLE
Editing navbar padding

### ISSUE THREAD

**Issue by Jnss98b** [Magisk-Modules-Repo/G-VisualMod#15]
Is there a way to reduce the vertical paddings of the navbar? In the screenshot it looks small but in real life the padding is a bit too much for my likings

![Screenshot_20210129-115252](https://user-images.githubusercontent.com/24306400/106303855-a5836e00-6228-11eb-833b-bf29db03a222.png)

**Comment by Gnonymous7** [comment]
Yeah but it'll be complicated if i leave that to user

**Comment by Jnss98b** [comment]
Oh so you can't give a few presets? I feel like the current padding is just a bit too much but I think there's someone out there who thinks it's enough so I wasn't thinking about the hardcoded change

**Comment by Gnonymous7** [comment]
I'll add it if i have free time

**Comment by Jnss98b** [comment]
I would appreciate that a lot thank you

**Comment by imyourgege** [comment]
i have reduced instead of making it an options, because its really that compilcated. hope you can accept this

**Comment by LuminarySage** [comment]
That should work thank you
