### ISSUE TITLE
Does not work in OxygenOS 11 and a suggestion

### ISSUE THREAD

**Issue by Camarada-Gabe** [Magisk-Modules-Repo/G-VisualMod#16]
Hello! Although it doesn't especify the versions, it says that OxygenOS is supported. But the quick settings or volume panel don't get rounded. Just system cards get as rounded as I chose in terminal. I am using OxygenOS v11.0.3.3.

The suggestion is to add some kind of translucent/transparent mode to the quick settings and status bar (blur effect would be great too).

Thank you!

**Comment by Gnonymous7** [comment]
Can you test my older builds for rounded? 3.1.1 or 2.x
And for the translucent, I'll keep it first until at least 5 or more users want this

**Comment by n00bmaster99** [comment]
Have u changed accent color or qs icon shape even once after factory reset this thing happening even on iOS 10
I also raise issue today Ui radius was working for me till I changed accent

**Comment by n00bmaster99** [comment]
> Can you test my older builds for rounded? 3.1.1 or 2.x
> And for the translucent, I'll keep it first until at least 5 or more users want this

Tried 3.1 didn't work for me

**Comment by imyourgege** [comment]
i dropped oxygen os since i cant install it on my current device
