### ISSUE TITLE
No more Ui radius after accent change

### ISSUE THREAD

**Issue by n00bmaster99** [Magisk-Modules-Repo/G-VisualMod#21]
Issue-  (ui radius don't work)
Rom-  (oxygen is 10.3.9)
I m facing one issue is that custom ui radius disappear after changing accent color in setting/customization/ accent color on oxygen is 10.3.9 . I have tried everything including reinstalling overlays and module too please help and don't know which logs u guys need to fix it.

**Comment by imyourgege** [comment]
change accent first then set gvm
