### ISSUE TITLE
Notchkiller high mobile data usage

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Repo/G-VisualMod#23]
![Screenshot_20210725-164744_Settings](https://user-images.githubusercontent.com/87975615/126971748-a5c75f1f-bfc0-4627-b43b-0cc4a97f77ee.png)
Why does this app use mobile data at all?

**Comment by imyourgege** [comment]
Sometimes the system may count the themed app's layer as its part and give fake statistics of the layer's data usage, which is impossible. In short, GVM does not use the Internet.
