### ISSUE TITLE
Pill Invisible Mode does not work in landscape mode

### ISSUE THREAD

**Issue by YiPrograms** [Magisk-Modules-Repo/G-VisualMod#3]
I've installed Pill Invisible Mod on my phone. It works well except the gesture pill reappears when the screen is in landscape mode.

Portrait mode: gesture pill is invisible
![Screenshot_20200221-023133](https://user-images.githubusercontent.com/16501891/74966706-3036d880-53dd-11ea-9d95-e15da219b068.jpg)

Landscape mode: gesture pill reappears
![Screenshot_20200221-023144](https://user-images.githubusercontent.com/16501891/74966770-552b4b80-53dd-11ea-8cfc-02bc6e400e33.jpg)

Device: OnePlus 6
Android: 10 (OxygenOS 10.3.1)
G-Visual: 2.1.1

**Comment by Gnonymous7** [comment]
Fix on upcoming update
