### ISSUE TITLE
Substratum themes overwrite UI radius mods

### ISSUE THREAD

**Issue by kotkreskowy** [Magisk-Modules-Repo/G-VisualMod#8]
Using a Substratum theme that changes the "Android system" overlay changes the UI radius on the notification panel to the stock value. Applying the themes first and installing the module second doesn't seem to do change anything, so is it perhaps some priority thing with Substratum having a higher priority than the module? 

If it matters, I'm on Pixel exp. 10 and the Substratum module is Ethereal.

**Comment by Gnonymous7** [comment]
yap, thats how substratum works. if you do substratum on the last... then priority goes to substratum
